# Generated by Django 2.0.5 on 2018-07-31 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_importuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom_id', models.IntegerField(default=0)),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('numbers', models.IntegerField(default=6)),
                ('opening', models.BooleanField(default=True)),
                ('assign', models.IntegerField(default=0)),
            ],
        ),
    ]
