# Generated by Django 2.0.5 on 2018-08-02 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_fclass_fcontent_fwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='domains',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='classroom',
            name='levels',
            field=models.TextField(default=''),
        ),
    ]
