# Generated by Django 2.0.5 on 2018-08-04 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_domain_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='like',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='profile',
            name='reply',
            field=models.FloatField(default=0.0),
        ),
    ]
