# Generated by Django 2.0.7 on 2018-08-03 13:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('annotation', models.TextField(default='')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('findex', models.IntegerField(default=0)),
                ('ftype', models.IntegerField(default=0)),
                ('mid', models.IntegerField(default=0)),
                ('stuid', models.IntegerField(default=0)),
                ('atype', models.IntegerField(default=0)),
            ],
        ),
    ]
